build:
  version: "1.0"

products:
  message: "Welcome to ISI Eshop products related PROD APIs "
  contactDetails:
    name: "Mamadou Bobo DIALLO - Product Owner"
    email: "boboisidk@groupeisi.com"
  onCallSupport:
    - 00 221 77 441 94 67
    - 00 221 76 232 66 46
